[IV-22-23] Objetivo 1
PabloSpiegel/WikiDisp pull request #13
Opened 2022-10-20 17:19 UTC by PabloSpiegel

# Prerrequisitos
* [x] Haber realizado el objetivo 1

# Lista de comprobacíón
## Sobre milestones
* [x] ¿Las historias de usuario y los milestones constituyen una guía
    suficiente para poder comenzar el desarrollo de un proyecto?
* [x] ¿Los milestones están ordenados correctamente, de forma que el 1 o
   0 sea lo primero que hay que empezar a publicar?
* [x] ¿Todos los milestones se construyen sobre el anterior, teniendo un
   orden lógico el desarrollo?
* [x] ¿El milestone 0 tiene asignada alguna historia de usuario?
* [x] ¿El milestone 0 corresponde con lo mencionado varias veces en
   clase, y en concreto con lo que se solicita en el objetivo
   siguiente?
* [x] ¿Todos los milestones describen correctamente un producto, y no un
   concepto vago, una funcionalidad o una tarea?
* [x] ¿Los milestones son graduales, o hay un salto grande entre ellos?
* [x] ¿Los milestones iniciales son internos, y hay a continuación milestones o
   productos externos?
* [x]  ¿Los milestones son mínimos, es decir, incluyen un producto
   mínimamente viable para poder avanzar?
* [x]  ¿El milestone 0 es mínimo *y* viable?
* [x]  ¿Se indica claramente cómo comprobar la viabilidad del PMV de cada hito? Es
    decir, ¿se dice qué requisitos técnicos tiene que cumplir el producto de
    cada hito?
* [x] ¿Entre dos milestones consecutivos, no hay ningún PMV posible o por el
    contrario podrían desarrollarse muchas posibles etapas internas o externas
    de un proyecto?

## Sobre historias de usuario
* [x] ¿He tenido en cuenta en las historias de usuario que se trata de un
   proyecto que se desplegará en la nube?
* [x] ¿Están descritos todos los conceptos mencionados en las HUs con
   suficiente claridad, generalmente en documentos aparte?
* [x] ¿Tienen coherencia suficiente las historias de usuario, y en caso
   de que no lo tengan, se ha escrito un *user journey* para
   aclararlo?
* [x] ¿Todas las historias de usuario representan un beneficio para el
    mismo y se relacionan con la lógica de negocio? Es decir, ¿los usuarios
    *desean* hacerlo o tú deseas que el usuario te lo pida para hacerlo?

2022-10-21 08:15 UTC, MauronMP commented
Buenas, me ha tocado de revisor de tú repositorio. He visto que has creado issues que no son historias de usuario, deberías de quitarlo y dejar sólo el HU001 que has creado

2022-10-21 08:26 UTC, marcosrmartin commented on docs/user-stories.md
> + - [HU001] [María](personas.md#María Peña) María quiere saber las diferencias existentes entre idiomas para determinadas categorías, más allá de lo que se puede ver cambiado de un artículo oa otro, m
Intenta especificar un poco más que son las diferencias entre idiomas, ¿A qué te refieres con más allá?

2022-10-21 08:26 UTC, marcosrmartin commented on docs/milestones.md
> +[M0]: Creación de Lista de idiomas y Diccionario/mapa que relacione países con sus idiomas<!--Idiomas: 639 Países e ISO 3166 para los paises-->
En los milestones no se definen el tipo de estructura de datos a utilizar.

2022-10-23 08:11 UTC, JJ commented on docs/milestones.md
> +[M0]: Creación de Lista de idiomas y Diccionario/mapa que relacione países con sus idiomas<!--Idiomas: 639 Países e ISO 3166 para los paises-->
Y tienes que decir claramene qué fase de solución del problema vas a abordar.

2022-10-27 07:35 UTC, PabloSpiegel commented
@MauronMP He borrado todos esos issues. Gracias por el apunte.

2022-10-27 07:50 UTC, PabloSpiegel commented on docs/user-stories.md
> + - [HU001] [María](personas.md#María Peña) María quiere saber las diferencias existentes entre idiomas para determinadas categorías, más allá de lo que se puede ver cambiado de un artículo oa otro, m
creo que lo he concretado mejor ahora. Muchas gracias por el apunte

2022-10-27 07:54 UTC, PabloSpiegel commented
@JJ listo para revisión

2022-10-27 08:00 UTC, JJ reviewed
Solo comentario, el resto te lo he dicho de palabra.

2022-10-27 08:00 UTC, JJ commented on README.md
> +##Descripción del problema
El anterior estaba bien; ahora no. Tiene que haber un espacio entre las marcas y la primera letra.

2022-10-27 08:00 UTC, JJ commented on README.md
> +La más simple sería introducir la URL de un artículo y dos idiomas, y que la aplicación calcule si hay mucha más cantidad de palabras en un idioma que en el otro. Para ese artículo también podría ana
Sería mejor que estos cambios los hicierais *antes* del objetivo; sólo añaden ruido a la corrección. Y más si no dividís el contenido en líneas de 80 caracteres.

2022-10-27 08:00 UTC, JJ commented
@fjromeero, @jesusjmma otra posibilidad de objetivo 1 que podéis revisar. Y una vez más, lo antes posible.

2022-10-27 08:31 UTC, jesusjmma commented
Hola @PabloSpiegel, soy Jesús Maldonado y voy a echarte una mano revisando.

2022-10-28 14:45 UTC, PabloSpiegel commented
@JJ Listo para revisión

2022-10-29 07:30 UTC, JJ requested changes
Como siempre, tenéis que tratar de entender que esto que escribís es una guía para la persona que trabaje en el objetivo 2; no tratéis de convertirlo en algo académico sino en algo eminentemente práctico para que una persona trabaje

2022-10-29 07:30 UTC, JJ commented on README.md
> +La más simple sería introducir la URL de un artículo y dos idiomas, y que la aplicación calcule si hay mucha más cantidad de palabras en un idioma que en el otro. Para ese artículo también podría ana
⬆️

2022-10-29 07:30 UTC, JJ commented on docs/milestones.md
> +[M0]: Lo que maría necesita es introducir un enlace a un artículo o a una categoría, seleccionar unos idiomas y que el programa haga análisis sobre estos.
Los milestones se formulan como productos, no deseos del cliente. Por favor, lee la documentación sobre productos mínimamente viables.

2022-10-29 07:30 UTC, JJ commented on docs/milestones.md
> +Este hito se considerará realizado cuando en el código se guarden debidamente los artículos, los idiomas y las categorías.
Esta descripción sería más correcta, pero en ingeniería la precisión en las descripciones es importante. En todo caso, esto no corresponde a lo anterior, ni explica qué fase del desarrollo sería suficiente para satisfacerlo. Sigues mencionando explícitamente artículos, idiomas y categorías que pueden o no ser parte del modelo del problema.

2022-10-29 07:30 UTC, JJ commented on docs/milestones.md
> +[M1]: A [María](user-stories.md#HU001)(a le agilizaría su trabajo saber cada selección que hace qué idioma tiene más contenido, cuál usa más referencias respecto a los demás, y cuál tiene menos vanda
Sigue siendo una historia de usuario, no un producto mínimamente viable. El producto que hay que entregar no está claro. Los milestones tienen que trabajar con historias de usuario, pero como ya expliqué en clase, son dos ejes de desarrollo diferentes: las HUs están en el eje del problema, los PMVs o hitos en el eje de la implementación

2022-10-29 07:30 UTC, JJ commented on docs/milestones.md
> +Este hito se considerará finalizado cuando se hayan implementado métodos que determinen para selección qué idioma cumple mejor cada uno de los criterios mencionados.
una vez más, esta descripción sería más adecuada, aunque convendría que se mencionara explícitamente la lógica de negocio o se hiciera un enlace a su descripción

2022-11-04 11:06 UTC, PabloSpiegel commented
@JJ Listo para revisión

2022-11-07 16:42 UTC, JJ approved these changes
Lo voy a dar por válido, pero empieza a trabajar inmediatamente en el objetivo siguiente y corrige lo comentado.

2022-11-07 16:42 UTC, JJ commented on docs/milestones.md
> +Este hito se considerará realizado cuando se tenga un modelo del problema válido implementado en un lenguaje que se vea apropiado.
Esto sería correcto, pero no tiene nada que ver con lo que pones arriba.

2022-11-10 08:18 UTC, merged